---
- name: Create a ec2 instance
  hosts: localhost
  gather_facts: False
  vars:
    key_name: Wordpress
    instance_type: t2.micro
    security_group: ['SSH' , 'Web Hosting']
    image: ami-f1978897
    region: eu-west-1
  tasks:
    - ec2:
         key_name: "{{ key_name }}"
         group: "{{ security_group }}"
         instance_type: "{{ instance_type }}"
         image: "{{ image }}"   
         wait: yes
         wait_timeout: 500      
         volumes:
          - device_name: /dev/sda1
            volume_type: gp2
            volume_size: 10
         region: "{{ region }}"
         vpc_subnet_id: subnet-78213020
      register: ec2
    - name: Add new instance to host group
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: launched
      with_items: "{{ ec2.instances }}"
    - name: Wait for SSH to come up
      wait_for:
        host: "{{ item.public_dns_name }}"
        port: 22
        delay: 60
        timeout: 320
        state: started
      with_items: "{{ ec2.instances }}"
